all:
	./db_merge.js ../db_books/db_books.json \
		../db_authors/db_authors.json \
		../db_readers/db_readers.json \
		../db_genres/db_genres.json \
		../db_languages/db_languages.json \
			db_catalog.json
clean:
	rm -f *.json
