all:
	cd db_authors;make
	cd db_readers;make
	cd db_genres;make
	cd db_languages;make
	cd db_merge;make
clean:
	cd db_authors; make clean
	cd db_readers; make clean
	cd db_genres; make clean
	cd db_languages; make clean
	cd db_merge; make clean
